version: 1.0.{build}
branches:
  only:
  - master
build_script:
- ps: ./build.ps1
test_script:
- ps: ./build.ps1 -test
before_deploy:
- ps: ./build.ps1 -pack
deploy:
- provider: Environment
  name: MyGet
  on:
    branch: master