version: 0.0.{build}
os: Visual Studio 2015
install:
- ps: dnvm install 1.0.0-rc1-update1
cache: C:\Users\appveyor\.dnx\packages
before_build:
- ps: dnu restore
build:
  verbosity: minimal
test_script:
- ps: script/test.ps1
